#!/bin/bash

# RENDER ENVIRONMENT VARIABLES UPDATE SCRIPT
# This script helps you update environment variables on Render

echo "🔧 RENDER SUPABASE ENVIRONMENT UPDATE GUIDE"
echo "============================================="
echo ""
echo "🎯 STEP 1: Go to Render Dashboard"
echo "   URL: https://render.com/dashboard"
echo ""
echo "🎯 STEP 2: Find your coogi-backend service"
echo "   Click on: coogi-backend-7yca"
echo ""
echo "🎯 STEP 3: Update Environment Variables"
echo "   Click: Environment (left sidebar)"
echo ""
echo "🎯 STEP 4: Update these SUPABASE variables:"
echo ""
echo "SUPABASE_URL=https://wbpuumoitoftzfqznwnq.supabase.co"
echo ""
echo "SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndicHV1bW9pdG9mdHpmcXpud25xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NDMxOTAsImV4cCI6MjA3MTIxOTE5MH0.wGWX3j4zCfLSGSNZBtKR8EoIjjfSVjY8VL1nY9_zlNs"
echo ""
echo "SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndicHV1bW9pdG9mdHpmcXpud25xIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NTY0MzE5MCwiZXhwIjoyMDcxMjE5MTkwfQ.9NwPfF2kH2CSlHwUutJJEER1tEprSS3K-Sqblnnb88M"
echo ""
echo "🎯 STEP 5: Save Changes"
echo "   Click: 'Save Changes' button"
echo "   Wait: 2-3 minutes for auto-redeploy"
echo ""
echo "🎯 STEP 6: Test the fix"
echo "   Run: curl https://coogi-backend-7yca.onrender.com"
echo "   Should show: API status without 401 errors"
echo ""
echo "✅ After updating, run this to test:"
echo "   ./test_supabase_production.sh"
