-- CRITICAL: Missing production_campaigns table
-- This table is required by your backend production_campaigns.py router

CREATE TABLE IF NOT EXISTS production_campaigns (
    id SERIAL PRIMARY KEY,
    campaign_id TEXT UNIQUE NOT NULL, -- Generated by backend: campaign_20250905_232435_2473
    name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft', -- draft, ready, active, paused, completed, error
    platform TEXT NOT NULL, -- instantly, smartlead, internal
    subject_line TEXT NOT NULL,
    from_email TEXT NOT NULL,
    from_name TEXT NOT NULL,
    email_sequence JSONB NOT NULL, -- Array of email steps
    target_count INTEGER DEFAULT 0,
    verified_contacts JSONB DEFAULT '[]'::jsonb, -- Array of contact objects
    sent_count INTEGER DEFAULT 0,
    open_count INTEGER DEFAULT 0,
    reply_count INTEGER DEFAULT 0,
    click_count INTEGER DEFAULT 0,
    bounce_count INTEGER DEFAULT 0,
    open_rate FLOAT DEFAULT 0.0,
    reply_rate FLOAT DEFAULT 0.0,
    click_rate FLOAT DEFAULT 0.0,
    provider_campaign_id TEXT, -- External provider ID
    agent_id TEXT, -- Link to progressive agent
    error_message TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_production_campaigns_campaign_id ON production_campaigns(campaign_id);
CREATE INDEX IF NOT EXISTS idx_production_campaigns_status ON production_campaigns(status);
CREATE INDEX IF NOT EXISTS idx_production_campaigns_platform ON production_campaigns(platform);
CREATE INDEX IF NOT EXISTS idx_production_campaigns_agent_id ON production_campaigns(agent_id);
CREATE INDEX IF NOT EXISTS idx_production_campaigns_created_at ON production_campaigns(created_at);

-- Row Level Security
ALTER TABLE production_campaigns ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all operations on production_campaigns" ON production_campaigns FOR ALL USING (true);
GRANT ALL ON production_campaigns TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE production_campaigns_id_seq TO anon, authenticated, service_role;

-- Test the table
INSERT INTO production_campaigns (campaign_id, name, platform, subject_line, from_email, from_name, email_sequence) VALUES 
('test_campaign_001', 'Test Campaign', 'instantly', 'Test Subject', 'outreach@coogi.ai', 'Coogi Team', '[{"step_number": 1, "subject": "Test", "body": "Test email", "delay_days": 0}]'::jsonb);

SELECT 'production_campaigns table created successfully!' as status;
SELECT COUNT(*) as test_rows FROM production_campaigns;
